import Head from 'next/head'
import Image from 'next/image' 
import { useRecoilState } from 'recoil'
import { sessionState } from '../atoms/session'
import InputComponent from '../components/InputComponent'
import LengthComponent from '../components/LengthComponent'
import styles from '../styles/Home.module.css'
import Login from './pagecomponents/login'

export default function Home() {
  // const[status]=useRecoilState(sessionState);
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
  {/* {status === "true" ? <Login/>:"opssssssssssssssssssssssss"}
   */}
   <Login/>
      {/* <InputComponent/>
      <LengthComponent/> */}
      
    </div>
  )
}
