import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Button, Col, Container, Form, Row } from 'react-bootstrap'
import loginImage from '../../images/login.png'
 
export default function Login() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Row className="m-0 p-0">

        <Col lg='6 m-auto'>
          <Container>
            <div className='p-5'>
              <form>
                <Form.Label htmlFor="mail">EMAIL ID</Form.Label>
                <Form.Control
                  type="email"
                  placeholder="Enter Your Email Id"
                  id="mail"
                  aria-describedby="passwordHelpBlock"
                />
                <div className='p-2'></div>
                <Form.Label htmlFor="inputPassword5">PASSWORD</Form.Label>
                <Form.Control
                  type="password"
                  id="inputPassword5"
                  placeholder="Enter Your Password"
                  aria-describedby="passwordHelpBlock"
                />
                <div className='py-3'></div>
                <Button variant='primary' className='submt' type='submit'>LOGIN</Button>
              </form>
              <div className='p-2'></div>
              <div className="d-flex justify-content-between">
                <p>Don't have any account ? </p>
                <Link href='/pagecomponents/signup'>
                  <a className="text-decoration-none">SignUp Now!</a>
                </Link>
              </div>
            </div>
          </Container>
        </Col>
        <Col lg='6'>
        <Image src={loginImage}/>
        </Col>
      </Row>
    

    </>
  )
}
