import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Button, Col, Container, Form, Row } from 'react-bootstrap'
import loginImage from '../../images/login.png'
import { useRef, useState } from 'react'
import Login from './login'

export default function SignUp() {
  const signUpForm = useRef(null);

  const handleClickEvent = () => {
    
    const form = signUpForm.current
   
    let userObj = {
      name: form['name'].value,
      email: form['email'].value,
      password: form['password'].value
    }
    console.log(JSON.stringify(userObj));
    signUpForm.current.reset();
  }

  return (
    <>
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Row className="m-0 p-0">

        <Col lg='6 m-auto'>
          <Container>
            <div className='p-5'>

              <form ref={signUpForm}>
                <Form.Label htmlFor="name">NAME</Form.Label>
                <Form.Control type="text" placeholder="Enter Your Name" id="name" name={"name"} />

                <div className='p-2'></div>
                <Form.Label htmlFor="mail">EMAIL ID</Form.Label>
                <Form.Control type="email" placeholder="Enter Your Email Id" id="mail" name={'email'} />
                <div className='p-2'></div>
                <Form.Label htmlFor="inputPassword5">PASSWORD</Form.Label>
                <Form.Control type="password" id="inputPassword5" placeholder="Enter Your Password" name={'password'} />
                <div className='py-3'></div>
                <Button variant='primary' className='submt' onClick={handleClickEvent} >SignUp</Button>
              </form>
              <div className='p-2'></div>
              <div className="d-flex justify-content-between">
                <p>Enter you'r details above </p>
                <Link href='/'>
                  <a className="text-decoration-none">&lt; Back </a>
                </Link>
              </div>
            </div>
          </Container>
        </Col>
        <Col lg='6'>
          <Image src={loginImage} />
        </Col>
      </Row>


    </>
  )
 
}
